##### logging

# env: (dev | prod)
# dev - pretty logging with colors
# prod - log JSON
env: dev

# loglevel: (trace | debug | info | warn | error)
loglevel: debug

##### vantage
vantage_custom_provider_token: accss_crdntl_474e50f429175132
vantage_api_url: https://api.vantage.sh/v2

# scaleway
scaleway_api_url: https://api.scaleway.com
scaleway_org_id: 8811656d-67df-434f-b2b7-2b91f0f74633

#tags
tags:
  Product: WIHP
  Portfolio: DMP
  Platform: Scaleway