name: build

on:
    push:
        branches: [ 'main' ]
    pull_request:
        branches: [ 'main' ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: set up Go env
              uses: actions/setup-go@v4
              with:
                go-version: '1.22.2'

            - name: test
              run: go test .

            - name: build
              run: go build .