name: build

on:
    push:
        branches: [ 'main' ]
    pull_request:
        branches: [ 'main' ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: set up Go env
              uses: actions/setup-go@v4
              with:
                go-version: '1.22.2'

            - name: install deps
              run: go mod tidy

            - name: test
              run: go test -race -covermode atomic -coverprofile=covprofile -v .

            - name: Install goveralls
              run: go install github.com/mattn/goveralls@latest

            - name: coverage
              run: goveralls -coverprofile=covprofile -service=github
              env:
                COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

            - name: build
              run: go build -v .